In [1]:
import numpy as np
import pandas as pd
path = "/home/flo/Documents/Sequential_Fish/analysis/run7/result_tables/"

In [10]:
Acquisition = pd.read_feather(path + "/Acquisition.feather")
Gene_map = pd.read_feather(path + "/Gene_map.feather")
Detection = pd.read_feather(path + "/Detection.feather")
Cell = pd.read_feather(path + "/Cell.feather")
Spots = pd.read_feather(path + "/Spots.feather")

In [12]:
from Sequential_Fish.analysis.post_processing import Spots_filtering

Spots = Spots_filtering(
        Spots,
        filter_washout=True,
        segmentation_filter=True,
        Cell=Cell,
        Detection=Detection
    )

In [14]:
from Sequential_Fish.analysis.colocalisation import colocalisation_truth_df, compute_z_score_frame

In [ ]:
truth_df = colocalisation_truth_df(
    Spots,
    Acquisition,
    Detection,
    Gene_map,
    Cell,
)
truth_df

,AGO1,AGO2,CHERD,EP400,GTF3C1,INO80,PCF11,POLR1A,POLR2A,POLR2B,POLR3A,SCAF4,SCAF8,SRCAP,spot_id,location,target,coordinates
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,Location-01,POLR2A,"(1000, 9021, 155200)"
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1,Location-01,POLR2A,"(1000, 11931, 157625)"
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2,Location-01,POLR2A,"(1000, 12416, 158498)"
3,False,False,False,False,False,False,False,False,False,True,False,False,False,False,4,Location-01,POLR2A,"(1000, 15229, 160050)"
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,76,Location-01,POLR2A,"(1200, 17072, 156267)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316788,True,False,False,False,False,False,False,False,False,False,False,False,False,False,374055,Location-10,AGO1,"(8200, 177510, 127458)"
316789,False,False,False,False,False,False,False,False,False,False,False,False,False,False,373818,Location-10,AGO1,"(1200, 5723, 64505)"
316790,False,True,False,False,False,False,False,False,False,False,False,False,False,False,373819,Location-10,AGO1,"(1600, 5820, 64505)"
316791,True,False,False,False,False,False,False,False,False,False,False,False,False,False,373957,Location-10,AGO1,"(6800, 12319, 65960)"
316792,True,False,False,False,False,False,False,False,False,False,False,False,False,False,373958,Location-10,AGO1,"(7000, 12416, 65863)"

In [21]:
rna_list = truth_df['target'].unique().tolist()
for rna in rna_list :
    truth_df.loc[truth_df['target'] == rna, [rna]] = True
truth_df

,AGO1,AGO2,CHERD,EP400,GTF3C1,INO80,PCF11,POLR1A,POLR2A,POLR2B,POLR3A,SCAF4,SCAF8,SRCAP,spot_id,location,target,coordinates
0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,0,Location-01,POLR2A,"(1000, 9021, 155200)"
1,False,False,False,False,False,False,False,False,True,False,False,False,False,False,1,Location-01,POLR2A,"(1000, 11931, 157625)"
2,False,False,False,False,False,False,False,False,True,False,False,False,False,False,2,Location-01,POLR2A,"(1000, 12416, 158498)"
3,False,False,False,False,False,False,False,False,True,True,False,False,False,False,4,Location-01,POLR2A,"(1000, 15229, 160050)"
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,76,Location-01,POLR2A,"(1200, 17072, 156267)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316788,True,False,False,False,False,False,False,False,False,False,False,False,False,False,374055,Location-10,AGO1,"(8200, 177510, 127458)"
316789,True,False,False,False,False,False,False,False,False,False,False,False,False,False,373818,Location-10,AGO1,"(1200, 5723, 64505)"
316790,True,True,False,False,False,False,False,False,False,False,False,False,False,False,373819,Location-10,AGO1,"(1600, 5820, 64505)"
316791,True,False,False,False,False,False,False,False,False,False,False,False,False,False,373957,Location-10,AGO1,"(6800, 12319, 65960)"
316792,True,False,False,False,False,False,False,False,False,False,False,False,False,False,373958,Location-10,AGO1,"(7000, 12416, 65863)"

In [25]:
rna_idx = pd.Index(rna_list)
all_combinations = truth_df.apply(lambda x : rna_idx[x.loc[rna_list]].to_list(), axis=1).unique()

TypeError: unhashable type: 'list'