In [31]:
import pandas as pd

# BarcodeRule

In [32]:
path = "/media/SSD_floricslimani/Fish_seq/Davide/FakeRun/"
filename = "barcodes_rule.xlsx"

In [72]:
barcode_rule = pd.read_excel(path + f"/{filename}")
barcode_rule = barcode_rule.rename(columns={"Cycles" : "barcode"})
barcode_rule

    barcode    Name  RO
0         1   SFRP1   3
1         1    TPX2   3
2         1    THY1   3
3         1    PLK1   3
4         1  PRSS23   3
5         1   FSTL1   3
6         1   CCND1   3
7         2     AK4   6
8         2   RCAN1   6
9         2    NASP   6
10        2    LIPA   6
11        2    LRAT   6
12        2   CENPF   6
13        2    PLK1   6
14        3   SFRP1   1
15        4    LRAT   9
16        5   RCAN1   4
17        6    THY1  13
18        7  PRSS23   5
19        7     AK4   5
20        8   FSTL1  14
21        8   CENPF  14
22        9   CCND1   8
23        9    LIPA   8
24       10    NASP   7
25       10    TPX2   7
26       11   SFRP1   3
27       11    TPX2   3
28       11    THY1   3
29       11    PLK1   3
30       11  PRSS23   3
31       11   FSTL1   3
32       11   CCND1   3
33       12     AK4   6
34       12   RCAN1   6
35       12    NASP   6
36       12    LIPA   6
37       12    LRAT   6
38       12   CENPF   6
39       12    PLK1   6

In [73]:
barcode_rule = barcode_rule.groupby('Name')["barcode"].apply(list)
barcode_rule

Name
AK4           [2, 7, 12]
CCND1         [1, 9, 11]
CENPF         [2, 8, 12]
FSTL1         [1, 8, 11]
LIPA          [2, 9, 12]
LRAT          [2, 4, 12]
NASP         [2, 10, 12]
PLK1      [1, 2, 11, 12]
PRSS23        [1, 7, 11]
RCAN1         [2, 5, 12]
SFRP1         [1, 3, 11]
THY1          [1, 6, 11]
TPX2         [1, 10, 11]
Name: barcode, dtype: object

# Spots

In [35]:
from Sequential_Fish.tools import safe_merge_no_duplicates

In [36]:
Acquisition = pd.read_feather(path + f"/result_tables/Acquisition.feather")
Gene_map = pd.read_feather(path + f"/result_tables/Gene_map.feather")
Acquisition = safe_merge_no_duplicates(Acquisition, Gene_map, keys=["cycle", "color_id","target"], on=["cycle"])
Acquisition

,acquisition_id,location,cycle,full_path,fish_shape,fish_map,bead_channel,dapi_channel,pipeline_version,fish_reodered_shape,Cycle n.,Gene0,Thresholds,color_id,target
0,0,Location-01,0,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",0,Barcode1,150,0,Barcode1
1,1,Location-01,1,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",1,Washout,200,0,Washout_1_0
2,2,Location-01,2,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",2,Barcode2,200,0,Barcode2
3,3,Location-01,3,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",3,Washout,95,0,Washout_3_0
4,4,Location-01,4,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",4,Barcode3,95,0,Barcode3
5,5,Location-01,5,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",5,Washout,95,0,Washout_5_0
6,6,Location-01,6,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",6,Barcode4,95,0,Barcode4
7,7,Location-01,7,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",7,Washout,50,0,Washout_7_0
8,8,Location-01,8,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",8,Barcode5,50,0,Barcode5
9,9,Location-01,9,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",9,Washout,100,0,Washout_9_0
10,10,Location-01,10,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",10,Barcode6,100,0,Barcode6
11,11,Location-01,11,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",11,Washout,150,0,Washout_11_0
12,12,Location-01,12,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",12,Barcode7,150,0,Barcode7
13,13,Location-01,13,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",13,Washout,65,0,Washout_13_0
14,14,Location-01,14,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",14,Barcode8,65,0,Barcode8
15,15,Location-01,15,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",15,Washout,80,0,Washout_15_0
16,16,Location-01,16,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",16,Barcode9,80,0,Barcode9
17,17,Location-01,17,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",17,Washout,100,0,Washout_17_0
18,18,Location-01,18,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",18,Barcode10,100,0,Barcode10
19,19,Location-01,19,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",19,Washout,180,0,Washout_19_0
20,20,Location-01,20,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",20,Barcode11,180,0,Barcode11
21,21,Location-01,21,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",21,Washout,135,0,Washout_21_0
22,22,Location-01,22,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",22,Barcode12,135,0,Barcode12
23,23,Location-01,23,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",23,Washout,150,0,Washout_23_0
24,24,Location-01,24,/media/SSD_floricslimani/Fish_seq/Davide/FakeR...,"[61, 2, 1981, 2004]","{'c': 2, 'cycles': 0, 'x': 4, 'y': 3, 'z': 1}",None,-1,0.1,"[61, 1981, 2004, 2]",24,Barcode13,150,0,Barcode13

In [60]:
Spots = pd.read_feather(path + f"/result_tables/Spots.feather")
Spots = safe_merge_no_duplicates(Spots,Acquisition, on= ["acquisition_id","color_id"], keys=["location","target"])
Spots

,spot_id,cluster_id,intensity,population,detection_id,cycle,color_id,is_washout,coordinates,acquisition_id,...,drift_z,drift_y,drift_x,z,y,x,in_nucleus,cell_label,location,target
0,0,0.0,4044,clustered,1,0,0,False,"[8, 1232, 571]",0,...,0,0,0,8,1232,571,True,19.0,Location-01,Barcode1
1,1,NaN,5909,free,1,0,0,False,"[9, 970, 444]",0,...,0,0,0,9,970,444,True,13.0,Location-01,Barcode1
2,2,NaN,7050,free,1,0,0,False,"[9, 1294, 1680]",0,...,0,0,0,9,1294,1680,False,15.0,Location-01,Barcode1
3,3,NaN,6787,free,1,0,0,False,"[9, 1306, 1690]",0,...,0,0,0,9,1306,1690,False,15.0,Location-01,Barcode1
4,4,NaN,8177,free,1,0,0,False,"[9, 1316, 1684]",0,...,0,0,0,9,1316,1684,False,15.0,Location-01,Barcode1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789293,789564,NaN,713,free,25,24,0,False,"[40, 950, 1219]",24,...,0,6,6,40,956,1225,False,0.0,Location-01,Barcode13
789294,789565,NaN,759,free,25,24,0,True,"[41, 371, 1050]",24,...,0,6,6,41,377,1056,False,2.0,Location-01,Barcode13
789295,789566,NaN,851,free,25,24,0,False,"[41, 394, 1233]",24,...,0,6,6,41,400,1239,False,0.0,Location-01,Barcode13
789296,789567,NaN,675,free,25,24,0,True,"[53, 40, 1681]",24,...,0,6,6,53,46,1687,False,0.0,Location-01,Barcode13
789297,789568,NaN,596,free,25,24,0,True,"[54, 40, 1681]",24,...,0,6,6,54,46,1687,False,0.0,Location-01,Barcode13

In [61]:
Spots["target"] = Spots["target"].str.replace("Barcode","")
Spots

,spot_id,cluster_id,intensity,population,detection_id,cycle,color_id,is_washout,coordinates,acquisition_id,...,drift_z,drift_y,drift_x,z,y,x,in_nucleus,cell_label,location,target
0,0,0.0,4044,clustered,1,0,0,False,"[8, 1232, 571]",0,...,0,0,0,8,1232,571,True,19.0,Location-01,1
1,1,NaN,5909,free,1,0,0,False,"[9, 970, 444]",0,...,0,0,0,9,970,444,True,13.0,Location-01,1
2,2,NaN,7050,free,1,0,0,False,"[9, 1294, 1680]",0,...,0,0,0,9,1294,1680,False,15.0,Location-01,1
3,3,NaN,6787,free,1,0,0,False,"[9, 1306, 1690]",0,...,0,0,0,9,1306,1690,False,15.0,Location-01,1
4,4,NaN,8177,free,1,0,0,False,"[9, 1316, 1684]",0,...,0,0,0,9,1316,1684,False,15.0,Location-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789293,789564,NaN,713,free,25,24,0,False,"[40, 950, 1219]",24,...,0,6,6,40,956,1225,False,0.0,Location-01,13
789294,789565,NaN,759,free,25,24,0,True,"[41, 371, 1050]",24,...,0,6,6,41,377,1056,False,2.0,Location-01,13
789295,789566,NaN,851,free,25,24,0,False,"[41, 394, 1233]",24,...,0,6,6,41,400,1239,False,0.0,Location-01,13
789296,789567,NaN,675,free,25,24,0,True,"[53, 40, 1681]",24,...,0,6,6,53,46,1687,False,0.0,Location-01,13
789297,789568,NaN,596,free,25,24,0,True,"[54, 40, 1681]",24,...,0,6,6,54,46,1687,False,0.0,Location-01,13

In [70]:
Spots["coordinates"] = Spots["coordinates"].apply(tuple)
grid = Spots.groupby(["location","coordinates"]).agg({
    "target" : list,
    "is_washout" : max
})
grid = grid.loc[~grid["is_washout"]]
grid["target"] = grid["target"].apply(pd.unique)
grid["dim"] = grid["target"].apply(len)
grid, grid["dim"].unique()

/tmp/ipykernel_104426/1371051502.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grid = Spots.groupby(["location","coordinates"]).agg({
/tmp/ipykernel_104426/1371051502.py:7: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  grid["target"] = grid["target"].apply(pd.unique)

(                                target  is_washout  dim
 location    coordinates
 Location-01 (5, 133, 1376)        [11]       False    1
             (5, 285, 1097)         [3]       False    1
             (5, 289, 1168)        [12]       False    1
             (5, 290, 1157)    [11, 12]       False    2
             (5, 292, 1144)        [11]       False    1
 ...                                ...         ...  ...
             (52, 1199, 521)        [8]       False    1
             (52, 1205, 1408)      [10]       False    1
             (57, 1196, 519)        [6]       False    1
             (59, 1202, 521)        [6]       False    1
             (59, 1205, 523)        [6]       False    1

 [48461 rows x 3 columns],
 array([1, 2, 3, 4, 5]))

In [71]:
grid[grid["dim"] > 1]

                                target  is_washout  dim
location    coordinates
Location-01 (5, 290, 1157)    [11, 12]       False    2
            (5, 337, 1172)    [10, 12]       False    2
            (5, 358, 1191)    [10, 12]       False    2
            (5, 396, 114)      [2, 11]       False    2
            (5, 402, 154)      [8, 12]       False    2
...                                ...         ...  ...
            (46, 1237, 1693)  [10, 11]       False    2
            (47, 457, 1145)   [11, 12]       False    2
            (47, 1201, 520)     [7, 8]       False    2
            (47, 1202, 521)    [8, 12]       False    2
            (47, 1203, 522)     [5, 8]       False    2

[539 rows x 3 columns]

In [74]:
barcode_rule

Name
AK4           [2, 7, 12]
CCND1         [1, 9, 11]
CENPF         [2, 8, 12]
FSTL1         [1, 8, 11]
LIPA          [2, 9, 12]
LRAT          [2, 4, 12]
NASP         [2, 10, 12]
PLK1      [1, 2, 11, 12]
PRSS23        [1, 7, 11]
RCAN1         [2, 5, 12]
SFRP1         [1, 3, 11]
THY1          [1, 6, 11]
TPX2         [1, 10, 11]
Name: barcode, dtype: object